titleInfo:
  fadeIn: 10
  stay: 70
  fadeOut: 20
biomeGroups:
  - ['birch_forest', 'old_growth_birch_forest']
  - ['taiga', 'old_growth_spruce_taiga', 'old_growth_pine_taiga']
  - ['these', 'biomes', 'wont', 'register', 'movement', 'between']
disabledRegions:
  - spawn
biomes:
  plains:
    title: 'Plains Biome!'
    subtitle: 'Vanilla biomes do not need namespaces'
    display: 'chat'
  "namespace:example":
    title: 'Example Biome!'
    subtitle: '3rd party biomes need namespaces'
    display: 'title'